ROOT = ../../../..

PROGS = cdnaEnsemblAligns cdnaPslEvidence estPslEvidence
cdnaEnsemblAligns_PROG_MODS = cdnaEnsemblAligns
cdnaPslEvidence_PROG_MODS = cdnaPslEvidence pslEvidCollect pslEvidence
estPslEvidence_PROG_MODS = estPslEvidence pslEvidCollect pslEvidence

include ${ROOT}/config.mk

include ${ROOT}/rules.mk
