ROOT = ../../../..

PROGS = cdnaPslEvidence estPslEvidence getUcscRnaAligns
cdnaPslEvidence_PROG_MODS = cdnaPslEvidence pslEvidCollect pslEvidence
estPslEvidence_PROG_MODS = estPslEvidence pslEvidCollect pslEvidence
getUcscRnaAligns_PROG_MODS = getUcscRnaAligns

include ${ROOT}/config.mk

include ${ROOT}/rules.mk
