* drop PY2 stuff (from future)
* the term `load' is getting confusing, use load and store, etc.
* tslGbffGetProblemCases should be run on cluster, drop multiprocessor mode.
* make clear genbank problem vs suspect (problem makes a gb suspect)
* should TSL not use RNAs with large initial/terminal unaligned sequence
  - coded added to evidFeatures.py, but currently ignored until TSL is validated
  - not clear if initial/terminal unaligned should be part of exon, as RnaInsertFeature,
    as now bounds preceeds rna coords in exon. Maybe unaligned should always be part of
    exons, not introns, maybe need a Gap StructureFeature.
* collect polyA predictions for RNA & eST
* add categories in previous TSL: code: mgcOrfeome, noStopClone
* what to do about the stop lists
* rename evidFeatures in objects to alignFeatures (although in analysis, it is still evidence)
* fine tune indel size based on where it occurs (UTR vs CDS), or weight evidence
  see tests/tsl/mondo/docs/cases.org

* mRNA attributes not being tag:
  - ofeomes  KJ891233.1 KJ894036.1 HQ447657.1
  - synthetic (e.g HQ447657)
  - noStopClone
* TSL details table would be much smaller if relational
* TSL details could just hold supporting data entries
* Annotations on patches UCSC doesn't have are just dropped, should get special code.
* Expand alignment tables to have orientInfo data
  - would have to compute on the fly for Ensembl
* TransFeatures could be immutable namedtuple if parent was found through a weak reference lookup table.
* Make TSL thresholds configurable
* is genePredIntrons needed any more?
* Add TSL override list, for things like 3-base exon
* change tranAnnot .chrom name to .chromRange or .chromCoords, or chromLoc
* mixing exon extension into status conflicts with good vs polymorphic.  
Make extends fuzzy.
* Make extend_exons not be poor
* Should record no_eval in results table so can be used with different versions of data
* possible bugs:
** ENST00000455238.1 - EST AI865129 should extend, however 5' of annotation is two bases longer.  ** ENST00000646142.1/ENSG00000284895.1 (AC119676.1)
REALLY PART OF
ENST00000372583.6/ENSG00000127124.16 (HIVEP3) ???  PROBABLY FINE!
** ENST00000414199.1 - LOOKS LIKE EST BQ011346 SHOULD SUPPORT? WHY NOT?
** Why Doesn EST AA029807 support ENST00000594546.1
** ENST00000455238.1 CHR1:48078787-48082196 ENSG00000231413.1
- should have had extend support: EST AI865129, HOWEVER 5' END IS 2 BASES LONGER
** ENSG00000228839.5/ENST00000440456.5 - antisense *
looks like it should be supported by EST BF439736
<<<<<<< Updated upstream
* doc RNA-Seqer
RNA-seqer API paper: https://academic.oup.com/bioinformatics/article/33/14/2218/3078600
Array Atlas paper: https://www.ncbi.nlm.nih.gov/pubmed/31665515.
