ROOT = ../../../..

PROGS = rslSpliceJunctionCollectEvidence
rslSpliceJunctionCollectEvidence_PROG_MODS = rslSpliceJunctionCollectEvidence intronCounts

include ${ROOT}/config.mk

include ${ROOT}/rules.mk

# Local Variables:
# mode: makefile-gmake
# End:
