ROOT = ../../../..

PROG_SRCS = spliceJunctionCollectEvidence.c intronCounts.c
PROG = spliceJunctionCollectEvidence

include ${ROOT}/config.mk

include ${ROOT}/rules.mk

# Local Variables:
# mode: makefile-gmake
# End:
