ROOT = ../../../..

PROGS = spliceJunctionCollectEvidence
spliceJunctionCollectEvidence_PROG_MODS = spliceJunctionCollectEvidence intronCounts

include ${ROOT}/config.mk

include ${ROOT}/rules.mk

# Local Variables:
# mode: makefile-gmake
# End:
